### ISSUE TITLE
ESC退出全屏后会自动进入网页全屏

### ISSUE THREAD

**Issue by IceNature** [spacemeowx2/DouyuHTML5Player#10]
使用的是脚本，Firefox 51 GM 3.9
全屏后按ESC并不会返回普通模式而是会进入网页全屏，只有再按一下ESC才能回到普通模式
不知道是BUG还是就是这样设计的

另还有一个问题使用Flash播放器时走到一半的弹幕全屏后弹幕还在，但HTML5播放器全屏后之前走到一般的弹幕全部消失

**Comment by spacemeowx2** [comment]
我偷懒没写好状态就这样了, 等我有空应该会全部修好=-= 最近比较忙

**Comment by spacemeowx2** [comment]
已解决

https://github.com/spacemeowx2/DouyuHTML5Player/blob/d43e61a7a34d762fdc253d33b7707589dec18385/src/danmuPlayer.ts#L79-L116
