### ISSUE TITLE
firefox 失效

### ISSUE THREAD

**Issue by kexul** [spacemeowx2/DouyuHTML5Player#16]
有弹幕，但是怎么都刷不出直播，，，，ｃｈｒｏｍｅ正常。
环境：Ｕｂｕｎｔｕ　１６．１０　
ｆｉｒｅｆｏｘ５３　
ｔｅｍｐｅｒｍｏｎｋｅｙ　４．３．５３９３
插件版本　０．５．５
不知道怎么ｄｅｂｕｇ呢？

**Comment by spacemeowx2** [comment]
为什么要用全角字符? 我都要瞎了

**Comment by kexul** [comment]
@spacemeowx2 抱歉，，，，没切成英文，，，

**Comment by spacemeowx2** [comment]
@kexul tempermonkey似乎不支持流fetch, 请用 GreaseMonkey 使用用户脚本
