### ISSUE TITLE
解决Mixed Content为什么不用URL.createObjectURL传递二进制数据

### ISSUE THREAD

**Issue by xinggsf** [spacemeowx2/DouyuHTML5Player#21]
URL.createObjectURL(blob);

**Comment by spacemeowx2** [comment]
欢迎提交PR

**Comment by xinggsf** [comment]
我看了你BLOG，里面讲“传递二进制数据”用base64转化，没必要，用URL.createObjectURL(blob || binArray)得到数据地址传给后台处理即可

**Comment by spacemeowx2** [comment]
base64是flash往js传数据的时候才用的, 解决 Mixed Content 是转成 Array 传的

**Comment by spacemeowx2** [comment]
另外你有没有考虑过 URL.createObjectURL 的效率问题? fetch拿到的数据每秒平均300-400KB, 还分不同的包, 每个包都createObjectURL的消耗有没有考虑过? 这可不是显示图片, 是传输数据

**Comment by xinggsf** [comment]
你BLOG
> 通过调试得知 flvjs 是通过 fetch 来获取视频流的, 于是方法是 Hook 掉 fetch 方法, 通过和 background 通信来获取数据, 再发给 flvjs. 不过有点坑的是, 和 background 通信只能传 json 数据, 因此 Uint8Array 在这个过程中要被转成 Array 再转回来, 感觉还是挺损失性能的.
这样不是二次转化吗？感觉消耗不低
createObjectURL 的消耗很低，其地址可用同步 XHR或fetch。

**Comment by xqq** [comment]
大量blob对象/句柄本身就是一个巨大的消耗
fetch每次给的分片是非常小的，最大就32k

**Comment by spacemeowx2** [comment]
你写个代码, 测试消耗比我这写法低就合并, 就这么简单

**Comment by sky0014** [comment]
其实就算是用base64，消耗也没多高，我试过了。

**Comment by spacemeowx2** [comment]
用代码说话
