### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by patrickzyc** [spacemeowx2/DouyuHTML5Player#22]
> node build/build.js

sh: 1: node: not found

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! douyu-html5-player@0.5.7 build: `node build/build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the douyu-html5-player@0.5.7 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the douyu-html5-player package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs douyu-html5-player
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls douyu-html5-player
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/patrick/下载/DouyuHTML5Player-master/npm-debug.log

**Comment by spacemeowx2** [comment]
把nodejs软链接到node
