### ISSUE TITLE
能否支持 Tampermonkey 和 Violentmonkey

### ISSUE THREAD

**Issue by ivysrono** [spacemeowx2/DouyuHTML5Player#23]
https://github.com/violentmonkey/violentmonkey/issues/107

爱奇艺那个html5脚本不支持GM，你们两个让世界都分裂了😄

**Comment by spacemeowx2** [comment]
GM 能生效的原因应该是用了旧的插件API, 像 Tampermonkey 这种应该是用了类似 Chrome 的 API, 所以限制会比较多. 我在考虑使用 Flash 来解决跨域问题(听谦谦说效果还不错

**Comment by ivysrono** [comment]
用flash的话，没装flash的怎么办

**Comment by spacemeowx2** [comment]
没装Flash我也没办法, 被浏览器限制死了, 只有这几条路可以走. (其实可能可以用WebRTC, 不过效率可能比较感人

**Comment by ivysrono** [comment]
用这个脚本就是为了免Flash，如果愿意用Flash，干嘛还要装脚本呢。
至少我是更愿意忍受也许感人的性能。

**Comment by gooyie** [comment]
解决混合内容和跨域问题不是可以用 GM_xmlhttpRequest 吗？Tampermonkey 和 Violentmonkey 都支持 GM_xmlhttpRequest + arraybuffer 的，只不过是字符串和 arraybuffer 来回转换，效率怎样就不知道了……

**Comment by spacemeowx2** [comment]
@gooyie 前几天稍微看了下 Tampermonkey 是hook的时候没成功, 估计是执行时间点不对, 过几天有空再调调...

**Comment by fuchanghao** [comment]
现在firefox的tm依然是无法支持。

**Comment by spacemeowx2** [comment]
刚吃完Firefox的shi，调试体验非常差。。。
TampleMonkey不能播的原因是GM_xmlhttpRequest不支持moz-chunked-arraybuffer返回的Response，需要TM添加支持才行。

**Comment by spacemeowx2** [comment]
Violentmonkey 同理, 而且会炸内存...

**Comment by fuchanghao** [comment]
其实我在想现在很多都是采用web-api的extention，这样ff和chrome的版本还可以同时维护。

**Comment by spacemeowx2** [comment]
让这些基于 WebExtension 的 Monkey 都支持 moz-chunked-arraybuffer (针对目前的版本) 且支持 Streaming response body 的比如 GM_fetch (针对57以后的版本) 就行, 我的代码不用修改就能运行. 

过段时间给个代码片段, 只要让那些 Monkey 能正常运行这个片段基本就没问题.

**Comment by fuchanghao** [comment]
发现个新玩意：
用这个貌似可以直接用google的crx的扩展，实测也没有问题。

https://addons.mozilla.org/zh-CN/firefox/addon/chrome-store-foxified/

**Comment by spacemeowx2** [comment]
本来我就做了ff支持而且正在发布xpi。。去release下载安装就好

**Comment by spacemeowx2** [comment]
https://gist.github.com/spacemeowx2/00bc4e3eef955b778e53ab00a1095ad8

只要这个gist能在俩monkey上跑就能支持了(或者有别的GM_ api也行, 比如 GM_fetch

目前只有 Greasemonkey 能跑, 这就是不支持的原因

**Comment by xinggsf** [comment]
@gooyie @spacemeowx2 
可以拦截hls.js的xhr吗？以解决HTTPS页面的混合内容和跨域问题

**Comment by spacemeowx2** [comment]
@xinggsf 虽然不知道你想干啥但是js就是谁先来谁厉害 没有什么是不能hook的(

**Comment by ivysrono** [comment]
似乎已经官方默认支持HTML5了，除了首页。
