### ISSUE TITLE
火狐能不能做成扩展，像chrome那样点击图标切换很方便

### ISSUE THREAD

**Issue by zhanxiage233** [spacemeowx2/DouyuHTML5Player#24]
因为斗鱼颜值区很多的直播间视频源如果不是超清就播放不出来，要禁用脚本或者右键切换清晰度和线路才能正常播放

**Comment by spacemeowx2** [comment]
更新一次审核一个月

**Comment by zhanxiage233** [comment]
@spacemeowx2 可以像 Youku-HTML5-Player这个作者一样，先提交审核，同时github提供签名的扩展文件直接安装 希望大神可以考虑考虑

**Comment by ivysrono** [comment]
这可能是解决#23 的最佳方案

**Comment by gooyie** [comment]
火狐内容脚本不会出现混合内容，做成扩展就可以不用从后台获取数据而产生额外消耗，效率比较好。
我自签了一个，用起来还不错。

https://github.com/gooyie/DouyuHTML5Player/commit/b5754905def9bfa613b66fe3a35df784ce48e6e0
[html5-0.5.8-an+fx-windows.xpi.zip](https://github.com/spacemeowx2/DouyuHTML5Player/files/1148322/html5-0.5.8-an.fx-windows.xpi.zip)

**Comment by xinggsf** [comment]
@spacemeowx2
@gooyie 
你们怎么做flash的逆向分析，什么工具？有什么资源推荐？谢谢

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/DouyuHTML5Player/releases

**Comment by spacemeowx2** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/douyuhtml5player/

**Comment by ivysrono** [comment]
0.7.4 版啥用没有？
