### ISSUE TITLE
Can't be used any longer

### ISSUE THREAD

**Issue by Reapor-Yurnero** [spacemeowx2/DouyuHTML5Player#30]
Seems Douyu has an update on it's mechanism and now this plugin can not successfully replace the flash player with html5 player. This happens for many people I know so I guess this should not be my own devices' problem.

**Comment by p1gd0g** [comment]
Douyu update api.

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/DouyuHTML5Player/blob/master/README.md

**Comment by spacemeowx2** [comment]
0.6.0 should work
