### ISSUE TITLE
斗鱼首页出现原生HTML5 Beta播放器

### ISSUE THREAD

**Issue by TinkoLiu** [spacemeowx2/DouyuHTML5Player#32]
斗鱼首页推荐位右键菜单出现试用HTML5播放器
但仍然加载了两个swf `ClientProxyIndex.swf` 和 `indexnetcore.swf`
是否有可能通过在房间内调用这两个swf实现获取播放地址？

另外主页上仅有 `ClientProxyIndex.swf` 在播放后实际留存，不负责任瞎猜，主要逻辑可能在这个swf。

**Comment by spacemeowx2** [comment]
之前其实就有能力直接调用他的swf进行签名, 只是需要flash插件被启用, 正在考虑在用flash的情况下直接调用swf来暂时解决问题

**Comment by Justsoos** [comment]
http://122.143.6.50/tc-tct.douyucdn.cn/dyliveflv3a/1321478ryrY7BRta.flv?wsAuth=e36b0ce9e34f37c254b6865f52f14679&token=webh5-1973891-1321478-bddba76802d156eafe9057df89c6ee51&logo=0&expire=0&did=10393286487835C67A6638DC955E6D18&ver=Douyu_h5_2017070401beta&dispatch_from=ztc10.124.81.201&utime=1501225224180

形如这样的，其实还是 flv，本地解了（可能用的flv.js）用html5 浏览器播放。看地址格式，此加密 api 和原来的flash 解码 flv 的 api 不会有大变化。

**Comment by spacemeowx2** [comment]
的确是flv.js, 他们写了个flash-stream-loader来解决mixed content问题 https://github.com/sky0014/flv.js/blob/master/src/io/flash-stream-loader.js 可以认为是同一份代码

**Comment by winnoryder** [comment]
没找到斗鱼有原生播放器，是在视频里面右键单击出现的吗？

**Comment by spacemeowx2** [comment]
现在版本用的swf已经是首页那个了(因为比较小)
