### ISSUE TITLE
能否转成扩展

### ISSUE THREAD

**Issue by omnjpa27516** [spacemeowx2/DouyuHTML5Player#36]
现在 GM 里就剩这一个钉子户脚本没法被替代了……
能否转成扩展（只签名就可以了），或者支持下 TM 也可以，希望作者考虑下~~

附带反馈一个问题，手机直播的房间，画面和声音都会卡。

**Comment by spacemeowx2** [comment]
xpi:
https://github.com/spacemeowx2/DouyuHTML5Player/releases/tag/v0.7.0
