### ISSUE TITLE
火狐扩展版不兼容52？

### ISSUE THREAD

**Issue by ghost** [spacemeowx2/DouyuHTML5Player#38]
脚本版正常，扩展版的播放器加载不正常，但右击黑屏画面可以出现画质，透明度等选项
火狐版本52.3，把其它扩展全禁用，只留斗鱼html5扩展也是一样不行

试了火狐56b7版本，扩展正常使用

**Comment by spacemeowx2** [comment]
可以发一下F12的log吗

**Comment by myskn** [comment]
query Array [ false ]  douyuCS.js:2546:27
SIGNER_READY true  douyuCS.js:2836:11
RoomId 74751  douyuInject.js:1091:27
onVideoId Object { roomId: "74751", id: "douyu_room_flash_proxy" }  douyuCS.js:2849:23
TypeError: setting is undefined
堆栈跟踪：
getSetting/</<@jar:file:///D:/software/Browser/Profiles/extensions/%7B4ff5f065-26f5-4595-a4de-b78ca1b769ab%7D.xpi!/dist/douyuCS.js:471:27
step@jar:file:///D:/software/Browser/Profiles/extensions/%7B4ff5f065-26f5-4595-a4de-b78ca1b769ab%7D.xpi!/dist/douyuCS.js:79:20
verb/<@jar:file:///D:/software/Browser/Profiles/extensions/%7B4ff5f065-26f5-4595-a4de-b78ca1b769ab%7D.xpi!/dist/douyuCS.js:60:55
fulfilled@jar:file:///D:/software/Browser/Profiles/extensions/%7B4ff5f065-26f5-4595-a4de-b78ca1b769ab%7D.xpi!/dist/douyuCS.js:50:50
  douyuCS.js:2903:23
<div class="jsocket-cls"> <object type="application/x-shockwave-flash" id="jsocket" name="jsocket" allowscriptaccess="always" allowfullscreen="true" allowfullscreeninteractive="true" wmode="transparent" data="https://imspace.nos-eastchina1.126.net/JSocket2.swf" width="100%" height="100%" align="middle">  douyuInject.js:127:19
Object { bodyUsed: false, ok: true, status: 200, statusText: "OK", type: "basic", url: "http://www.douyutv.com/swf_api/room…", headers: Object }  douyuCS.js:165:9
username auto_Bs89aoflqv 15093e578sf42f2ba84c675e89edbe4d  douyuInject.js:762:11
loginres 
dm Object { type: "loginres", userid: "0", roomgroup: "0", pg: "0", sessionid: "0", username: "", nickname: "", live_stat: "0", is_illegal: "0", ill_ct: "", 等 13 项… }  douyuInject.js:913:11

dm Object { type: "keeplive", tick: "1504251340", uc: "0", rap: "0" }  douyuInject.js:918:11
username auto_Bs89aoflqv 15093e578sf42f2ba84c675e89edbe4d  douyuInject.js:762:11
loginres 
ms Object { type: "loginres", userid: "1884349", roomgroup: "1", pg: "1", sessionid: "1377200500", username: "auto_Bs89aoflqv", nickname: "moha", live_stat: "1", is_illegal: "0", ill_ct: "", 等 12 项… }  douyuInject.js:840:11

ms Object { type: "cpn", cmd: "9", clist: "", cpt: "0", cps: "icpo@=0/iccp@=0/uinfo@=/win@=/hp@=0/" }  douyuInject.js:863:11

ms Object { type: "msgrepeaterlist", rid: "74751", list: "id@A=72952@Snr@A=1@Sml@A=10000@Sip@…" }  douyuInject.js:863:11

ms Object { type: "cmdlist", cmdlist: "查看投票结果/" }  douyuInject.js:863:11
joingroup Object { type: "setmsggroup", rid: "74751", gid: "1" }  douyuInject.js:854:11

ms Object { type: "scl", cd: "5", maxl: "20" }  douyuInject.js:863:11

ms Object { type: "suq", pd: "2500991de01d1d1d731d1d241d1d1b1df8f…" }  douyuInject.js:863:11

ms Object { type: "cdcp", pid: "3", cnt: "0", hpid: "43", hcnt: "0" }  douyuInject.js:863:11

ms Object { type: "rri", uid: "74751", rid: "74751", cate_id: "15", ri: "sc@=7425000/idx@=70/" }  douyuInject.js:863:11

ms Object { type: "rlcn", rn: "ctrnz", cate_id: "15", rls: "sc@A=158476100@Sidx@A=1@Srid@A=6737…", rid: "-1" }  douyuInject.js:863:11

ms Object { type: "blst", wf: "0", list: "", frq: "1" }  douyuInject.js:863:11

ms Object { type: "wiru", pos: "8", rid: "-1" }  douyuInject.js:863:11

ms Object { type: "qtlnr", ps: "0" }  douyuInject.js:863:11

exe Array [ "js_data_isAction", true ]  douyuInject.js:985:15

exe Array [ "js_effectVisible", 1 ]  douyuInject.js:985:15

exe Array [ "js_shieGiftEffect", 1 ]  douyuInject.js:985:15

exe Array [ "js_shieldEffects", "{"allGift":1,"message":1,"videoBroa…" ]  douyuInject.js:985:15

exe Array [ "js_data_server_shield", "type@=dmfbdreq/dfl@=sn@AA=105@ASss@…" ]  douyuInject.js:985:15

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

dm Object { type: "qausrespond", rid: "-1", sc: "608400", sctn: "61600" }  douyuInject.js:918:11

dm Object { type: "keeplive", tick: "1504251370", uc: "0", rap: "0" }  douyuInject.js:918:11

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

dm Object { type: "qausrespond", rid: "-1", sc: "608400", sctn: "61600" }  douyuInject.js:918:11

exe Array [ "js_data_isAction", true ]  douyuInject.js:985:15

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

dm Object { type: "qausrespond", rid: "-1", sc: "608300", sctn: "61700" }  douyuInject.js:918:11

dm Object { type: "keeplive", tick: "1504251400", uc: "0", rap: "0" }  douyuInject.js:918:11

dm Object { type: "qausrespond", rid: "-1", sc: "608300", sctn: "61700" }  douyuInject.js:918:11

dm Object { type: "keeplive", tick: "1504251430", uc: "0", rap: "0" }  douyuInject.js:918:11

dm Object { type: "qausrespond", rid: "-1", sc: "608300", sctn: "61700" }  douyuInject.js:918:11

dm Object { type: "keeplive", tick: "1504251460", uc: "0", rap: "0" }  douyuInject.js:918:11

exe Array [ "js_data_isAction", true ]  douyuInject.js:985:15

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

dm Object { type: "qausrespond", rid: "-1", sc: "608300", sctn: "61700" }  douyuInject.js:918:11

exe Array [ "js_data_isAction", true ]  douyuInject.js:985:15

exe Array [ "js_data_isAction", false ]  douyuInject.js:985:15

dm Object { type: "qausrespond", rid: "-1", sc: "608300", sctn: "61700" }  douyuInject.js:918:11

dm Object { type: "keeplive", tick: "1504251490", uc: "0", rap: "0" }

**Comment by spacemeowx2** [comment]
发现是 background.js 中的 emu 变为 undefined 造成的, 这方面日志需要在 CTRL+SHIFT+J 查看
