### ISSUE TITLE
0.7.1 QQ浏览器下无法使用

### ISSUE THREAD

**Issue by wilhelmTian** [spacemeowx2/DouyuHTML5Player#39]
前几天0.7.0在QQ浏览器下是可用的，0.7.1突然就不可用了……

background.js 88行 unexpected identifier错误

F12控制台： Uncaught (in promise) Error: Attempting to use a disconnected port 

如果开发者有精力可以测试一下，谢谢~

**Comment by spacemeowx2** [comment]
为什么不F12页面的信息呢? 这个错的意思是标签页已经关掉了所以background发不出去, 并没有有意义的信息
