### ISSUE TITLE
有些直播间卡的鬼畜了

### ISSUE THREAD

**Issue by zhanxiage233** [spacemeowx2/DouyuHTML5Player#40]
百分浏览器 64位 内核60 win7x64
看一些户外的手机直播的直播间，卡的鬼畜 切换成flash就没问题
反而看电脑直播的游戏直播间，这些直播间码率高但是正常

**Comment by spacemeowx2** [comment]
d1c45b88f60a311c0c26382566b786b8aa704388 应该好了
