### ISSUE TITLE
firefox扩展无法加载弹幕。

### ISSUE THREAD

**Issue by fuchanghao** [spacemeowx2/DouyuHTML5Player#45]
lawlietfox，开启了 Multiprocess Firefox

https://sourceforge.net/projects/lawlietfox/?source=navbar

UA：Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 

chrome版却正常，不知道原因如何。

**Comment by spacemeowx2** [comment]
Flash 是否正常加载?

**Comment by fuchanghao** [comment]
弹幕需要调用flash么？

斗鱼我没有允许FF调用flash在页面上。

**Comment by machsix** [comment]
@fuchanghao 先点地址栏里的html5标志使用flash播放器并remember，再换回html5播放器就好了，Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 测试没问题，感谢开发者！
