### ISSUE TITLE
firefox 升级到 57 以后脚本似乎失效了？

### ISSUE THREAD

**Issue by solor** [spacemeowx2/DouyuHTML5Player#47]
firefox 升级到了 57，具体版本号是57.0 b9
greasemonkey 的版本号是 4.0 alpha 7
脚本失效，一直黑屏
禁用 greasemonkey 试用了一下 violentmonkey 2.8.13 仍然是同样情况，一直黑屏
没升级 57 以前一切正常

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/DouyuHTML5Player/releases/download/v0.7.4/html5-0.7.4-an.fx.xpi

**Comment by solor** [comment]
一切正常了，感谢回复 ;)
