### ISSUE TITLE
chrome 弹幕无法加载

### ISSUE THREAD

**Issue by tigerhuhuhu** [spacemeowx2/DouyuHTML5Player#49]
右侧边栏为空白，包括榜单以及弹幕&礼物。

地址栏右侧一直显示flash被blocked但是在chrome://settings/content/flash下已经enable了flash。。很奇怪。。最新版的chrome里 chrome://flags/#run-all-flash-in-allow-mode  这个选项已经不存在了。

不加载html5player时地址栏右侧仍显示flash 被blocked，但是右侧边栏加载正常，弹幕以及榜单显示正常

**Comment by spacemeowx2** [comment]
Chrome版本是多少?

**Comment by luoxufeiyan** [comment]
同样的问题，地址栏右侧显示Flash被屏蔽，即便允许加载Flash插件也无法显示弹幕。

使用斗鱼默认的Flash播放器则正常显示。

Chrome版本： 62.0.3202.94
OS版本： Windows7专业版 Service Pack 1

页面看起来是这样的：
![页面看起来是这样的](http://ww1.sinaimg.cn/large/006IvTgQgy1fmffd76lq1j31hc0sw138.jpg)

![Console](http://ww1.sinaimg.cn/large/006IvTgQgy1fmffd74kzqj30t30n3gqv.jpg)

**Comment by spacemeowx2** [comment]
有出现lost connection说明flash已经成功加载了

**Comment by luoxufeiyan** [comment]
感谢回复。


发现这个问题似乎与宽带有关，我用的是移动宽带。同时间段使用电信宽带可以正常加载弹幕。而且似乎移动宽带在白天可以正常加载弹幕，晚上有很大几率加载失败，坐标浙江。修改hosts后就好了。

**Comment by Misaka-0x447f** [comment]
发现了同样问题。上海奠信，Chrome latest 63.0.3239.108 (Official Build) (64-bit)。

**Comment by HoweChen** [comment]
@luoxufeiyan 原来也是个猛男。。我用Canary也是一样无法加载弹幕，跟你一样的情况。然后我偶然间发现有一次加载成功了，不知道是不是我proxy设定的问题

**Comment by spacemeowx2** [comment]
估计是跨域授权的 xml 端口号问题, 要解决的话可能得改 swf. 之后有空会尝试

**Comment by spacemeowx2** [comment]
最新版用 WebSocket 连接了, 不再需要 Flash 了
