### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by tangzhenquan** [spacemeowx2/DouyuHTML5Player#50]
> douyu-html5-player@0.7.4 build /home/tom/Documents/test/douyu/DouyuHTML5Player
> node build/build.js

dist/danmu.css 7.51kb
Treating 'flv.js' as external dependency
Could not resolve 'TypeState' from /home/tom/Documents/test/douyu/DouyuHTML5Player/src/danmuPlayer.ts
Error: Could not resolve 'TypeState' from /home/tom/Documents/test/douyu/DouyuHTML5Player/src/danmuPlayer.ts
    at /home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:85:23

**Comment by spacemeowx2** [comment]
Did you run `npm install` ?

**Comment by tangzhenquan** [comment]
tom@seeyou-All-Series:~/Documents/test/douyu$ git clone https://github.com/spacemeowx2/DouyuHTML5Player.git
Cloning into 'DouyuHTML5Player'...
remote: Counting objects: 710, done.
remote: Total 710 (delta 0), reused 0 (delta 0), pack-reused 709
Receiving objects: 100% (710/710), 1.07 MiB | 485.00 KiB/s, done.
Resolving deltas: 100% (460/460), done.
Checking connectivity... done.
tom@seeyou-All-Series:~/Documents/test/douyu$
tom@seeyou-All-Series:~/Documents/test/douyu$ ls
DouyuHTML5Player
tom@seeyou-All-Series:~/Documents/test/douyu$ cd DouyuHTML5Player/
tom@seeyou-All-Series:~/Documents/test/douyu/DouyuHTML5Player$ ls
build  icon.png  icon.pxd  LICENSE  manifest.json  package.json  README.md  screenshot.jpg  src  tsconfig.json  typings
tom@seeyou-All-Series:~/Documents/test/douyu/DouyuHTML5Player$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
added 388 packages in 9.374s
tom@seeyou-All-Series:~/Documents/test/douyu/DouyuHTML5Player$ npm run build

> douyu-html5-player@0.7.4 build /home/tom/Documents/test/douyu/DouyuHTML5Player
> node build/build.js

dist/danmu.css 7.51kb
Treating 'flv.js' as external dependency
Could not resolve 'TypeState' from /home/tom/Documents/test/douyu/DouyuHTML5Player/src/danmuPlayer.ts
Error: Could not resolve 'TypeState' from /home/tom/Documents/test/douyu/DouyuHTML5Player/src/danmuPlayer.ts
    at /home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/rollup-plugin-node-resolve/dist/rollup-plugin-node-resolve.cjs.js:85:23
    at /home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:50:13
    at processDirs (/home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:182:39)
    at ondir (/home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:197:13)
    at load (/home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:80:43)
    at onex (/home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:105:17)
    at /home/tom/Documents/test/douyu/DouyuHTML5Player/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:153:21)

**Comment by spacemeowx2** [comment]
试着把danmuPlayer.ts里的大写TypeState改成小写

**Comment by tangzhenquan** [comment]
改成小写解决了，谢谢

**Comment by spacemeowx2** [comment]
下次我改下...Windows 不分大小写有点坑(
