### ISSUE TITLE
Danmaku repeats if you manages the room

### ISSUE THREAD

**Issue by TinkoLiu** [spacemeowx2/DouyuHTML5Player#51]
Danmaku will show twice if you are one of the managers of the room.

房管身份导致弹幕重复。

**Comment by mercury233** [comment]
我也有同样问题，原来可能是这个原因

**Comment by spacemeowx2** [comment]
我无法复现...

**Comment by spacemeowx2** [comment]
![default](https://user-images.githubusercontent.com/8019167/33704591-0c1a30fe-db68-11e7-9c7e-b56231ee615f.png)

**Comment by mercury233** [comment]
![image](https://user-images.githubusercontent.com/13391795/33710489-b03da0ae-db7b-11e7-89e3-8b9f6a61eaea.png)

可以邮件联系我提供账号

**Comment by TinkoLiu** [comment]
主播弹幕不会重复

**Comment by spacemeowx2** [comment]
就是说要房管看普通用户不重复是吗

**Comment by spacemeowx2** [comment]
那可能是斗鱼就是发了两遍, 其中一份是包含额外信息的需要过滤掉

**Comment by spacemeowx2** [comment]
![test](https://user-images.githubusercontent.com/8019167/33714525-34384022-db8a-11e7-8deb-3618e44024bf.png)
刚才手抖关了一下issue... 我让普通用户发还是无法重现.  @mercury233 我按github的地址发邮件提示找不到 
> 由于系统找不到电子邮件地址 me@mercury233.me

或者你直接发给我 spacemeowx2@gmail.com

**Comment by spacemeowx2** [comment]
Flash Player 里的判断是rg > 1 || pg > 1则忽略dm服务器的弹幕. 目前的修复方案是忽略ms服务器的弹幕, 副作用是可能遗漏部分弹幕, 等1.0版本(还在非常慢的写)的时候应该能彻底修复.

**Comment by spacemeowx2** [comment]
最新版(0.8.4)使用了 Flash 的忽略逻辑, 应该不会出现这个问题
