### ISSUE TITLE
firefox 58 beta + 暴力猴 , 脚本不工作

### ISSUE THREAD

**Issue by Remonli** [spacemeowx2/DouyuHTML5Player#52]
有没有计划更新支持呢?

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/DouyuHTML5Player/issues/23#issuecomment-330499851

重复

**Comment by spacemeowx2** [comment]
问题就是是monkey不支持stream fetch, 不是脚本不支持monkey
