### ISSUE TITLE
Flash 的问题

### ISSUE THREAD

**Issue by solor** [spacemeowx2/DouyuHTML5Player#54]
请问在禁用 Flash 的情况下，斗鱼直播页面个人信息和弹幕这些东西都无法加载是有意做成这样的么？
因为在 Firefox 上 Flash 的问题非常多，经常出现 CPU 占用过高甚至导致 Firefox 假死，所以我一直是禁用 Flash 的 ~~

**Comment by spacemeowx2** [comment]
换个说法, 不是有意做成这样的, 是这些信息就是只能通过Flash才能获得
