### ISSUE TITLE
0.81未开播房间 未能显示弹幕

### ISSUE THREAD

**Issue by hiwhm** [spacemeowx2/DouyuHTML5Player#66]
未开播的房间 我觉得应该也要把弹幕显示出来 平时也会存在一些热门主播 开播前的弹幕交流

**Comment by spacemeowx2** [comment]
你是说在视频的位置显示还是右侧

**Comment by hiwhm** [comment]
右侧显示的 礼物列表、贡献列表也是没显示的 嗯... 我去看源码 
DouyuClient->chatmsg() 能接收弹幕信息 但调用 ACJ() 未能在右侧显示
而平常正常显示的 DouyuDanmuClient->chatmsg() 未能接收信息
能力不足未能看懂.... 猜测原因
没能找到未开播房间直播流去加载flash api接口  但控制台_ACJ_(['room_data_chat2', data]) 能显示 接口应该是创建的了....

**Comment by spacemeowx2** [comment]
看看最新版有没有修复

**Comment by hiwhm** [comment]
0.83 目前能可以在 未开播时 加载出右侧弹幕区并能发送出弹幕（其他用户可以接收） 
但左右侧均未能显示和接收他人弹幕显示  
我想请求一下大大可以在代码上加上少量注释...

**Comment by spacemeowx2** [comment]
你的意思是视频区域没弹幕? 因为逻辑是这样视频没播放的时候弹幕是不会动的, 主要是在直播卡顿的时候弹幕会暂停发送等到播放时再按相对偏移时间发射.

你就说你哪看不懂吧我在这解释, 我的代码都没注释的...

**Comment by hiwhm** [comment]
我的意思是 右侧弹幕区同没有弹幕 进入房间欢迎词是有的 但没用户输入的弹幕
2333 有点尴尬 不懂的地方有点多  ~(>_<。)＼

**Comment by spacemeowx2** [comment]
噢复现了, 之前都在自己直播间没复现出来, 过段时间修

**Comment by hiwhm** [comment]
做下贡献 (*＾-＾*)
DouyuClient->chatmsg(); 加上 onChatMsg(data); 可以显示了

**Comment by spacemeowx2** [comment]
加上这个有房管的房间会有两重弹幕..

**Comment by spacemeowx2** [comment]
@hiwhm 需要有一定人气的房间才会发生, 你可以找一下那个issue

**Comment by spacemeowx2** [comment]
最新版(0.8.4)使用了 Flash 的忽略逻辑, 应该不会出现这个问题
