### ISSUE TITLE
看scboy  星际老流氓 弹幕一直在加载中 

### ISSUE THREAD

**Issue by WPH95** [spacemeowx2/DouyuHTML5Player#7]
如题
http://www.douyu.com/scboy

**Comment by spacemeowx2** [comment]
一直加载中是什么效果...听说最近斗鱼要多刷几次才能连进弹幕服务器, 试试刷新?

**Comment by misdake** [comment]
Chrome 56.0.2924.87
页面加载时右上角显示插件已被拦截，弹幕无法加载。
即使url左边i那里已经选择允许flash，且内容设置中Flash选择“允许网站运行Flash”，例外里已添加douyu.com和applinzi.com。
如果点击右上角提示，点击“运行所有插件（仅限此次）”之后，network看到加载JSocket.swf，随后弹幕正常加载。

**Comment by li77leprince** [comment]
我跟楼上的情况一样，点击“运行所有插件（仅限此次）”后可以看到弹幕。Win7+Chrome56

**Comment by spacemeowx2** [comment]
@li77leprince 不能选择一直运行吗?

**Comment by goldkeyber** [comment]
@spacemeowx2 chrome已经设置的例外情况，但是观看时falsh总是被屏蔽，只能选择点击“运行所有插件（仅限此次）”后可以看到弹幕，如果不设置例外情况连“运行所有插件选“项都没有。Windows 10 Chrome56

**Comment by brlala** [comment]
大家有没有方法看到弹幕了？

**Comment by spacemeowx2** [comment]
感觉很奇怪, 为什么斗鱼的 swf 就不会被屏蔽... 不过在我的几台电脑内都不会被屏蔽 @goldkeyber .

**Comment by spacemeowx2** [comment]
chrome://flags/#run-all-flash-in-allow-mode 开启这个似乎能不被屏蔽

**Comment by spacemeowx2** [comment]
只要 Flash 够大, 就不会被屏蔽. c9f79695136e0a79b456b74815f1944b4ce13d63
