### ISSUE TITLE
请问如何重置扩展选项？

### ISSUE THREAD

**Issue by qifei9** [spacemeowx2/DouyuHTML5Player#83]
Firefox

在右键菜单里选了纯净模式，结果现在右键菜单出不来了，请问如何能取消纯净模式呢？

**Comment by winnoryder** [comment]
卸载插件重装

**Comment by qifei9** [comment]
卸载插件重装没有用，依然是纯净模式，右键菜单闪一下就没了，没法把纯净模式点掉

**Comment by spacemeowx2** [comment]
临时的解决方法是在斗鱼页面打开F12, 在Application的localStorage里把带有pureMode的键删掉.

**Comment by qifei9** [comment]
突然发现这个问题只在标准的斗鱼页面存在，就是左侧有分类的那种页面，如果是特殊的房间页面，换了背景，左边没有分类的那种房间的页面，右键菜单是正常的，然后把纯净模式点掉就行了。

另外，还发现纯净模式会在标准页面引起鼠标手势的问题，也是和右键有关，出现的鼠标手势是乱的，而且会立刻消失，导致鼠标手势没法使用。我用的鼠标手势的插件是gesturefy。

**Comment by spacemeowx2** [comment]
因为右键菜单打开时会产生一个遮蔽层用来在你点击空白处的时候关闭菜单所以可能有兼容问题

**Comment by qifei9** [comment]
这些问题只在开启纯净模式的时候出现。总之，至少我遇到的问题已经解决了。谢谢两位。
