### ISSUE TITLE
你们好，麻烦能问一下斗鱼的音频流你们有了解嘛？

### ISSUE THREAD

**Issue by yyc-dev** [spacemeowx2/DouyuHTML5Player#84]
你们好，麻烦能问一下斗鱼的音频流你们有了解嘛？
斗鱼的音频流是怎么获取的呢？

**Comment by spacemeowx2** [comment]
这个应该是手机端才有的, 因此我们有逆向到, 且和项目无关.

**Comment by Justsoos** [comment]
貌似前阵子试过，垃圾斗鱼把视频流合并一起传到本地，在本地app上只解出音频。。。。非常白痴的行为。。。和u2b的技术真没法比。
自己要解，可以随便，用 mpv.exe --no-video 播放，就是这个效果。
