### ISSUE TITLE
请问扩展是否把“竞猜栏”屏蔽了？

### ISSUE THREAD

**Issue by waldens** [spacemeowx2/DouyuHTML5Player#88]
如果没有屏蔽，那汇报一个疑似bug，或是我本地问题？如果刻意屏蔽，是feature，请问能否提供开关？谢谢

测试页面：https://www.douyu.com/11017
环境：百分浏览器v3.5.3.50（正式版本） （64 位） (portable) (Chromium 67.0.3396.99) + Windows7 x64

重现步骤：
① 禁用全部扩展，包括“斗鱼HTML5播放器”
② 重启浏览器，访问https://www.douyu.com/11017 并登陆斗鱼账号
期望结果：可以看到竞猜
实际结果：可以看到竞猜 —— 正常
③ 仍然禁用其它扩展，只启用“斗鱼HTML5播放器”
④ 访问https://www.douyu.com/11017
期望结果：可以看到竞猜
实际结果：看不到竞猜 —— 不正常

![](http://onuia4d7l.bkt.clouddn.com/2018_08_26_20180826144046.png)

**Comment by spacemeowx2** [comment]
这是不刻意的屏蔽但是又不想做的功能, 因为竞猜实际上是打扰观看体验的, 并且要添加额外代码来支持的.

但是如果有人想竞猜的话我应该会抽时间做一个默认关闭的支持的.

**Comment by waldens** [comment]
@spacemeowx2 谢谢，明白了<img alt="ghe-emoji" title=":_tuzki_much_love:" src="https://cloud.githubusercontent.com/assets/136959/13371047/806073be-dce2-11e5-8e00-ce85c9f74425.gif"> 
其实我原以为，本扩展只是把播放器替换成HTML5，并不改变页面其它节点。原来还会影响竞猜栏。

观看体验的话，我是用css解决的：
https://userstyles.org/styles/138386/theme
平时极简，偶尔需要竞猜，用快捷键禁用stylus就行了

**Comment by waldens** [comment]
这个功能不怎么常用，优先级不高，就先关闭了
