### ISSUE TITLE
清晰度是如何定义的呢？

### ISSUE THREAD

**Issue by wangzhao2222** [spacemeowx2/DouyuHTML5Player#89]
该扩展中的“超清、高清、标清”如何映射原播放器的“蓝光8M、蓝光4M、高清、标清”？

**Comment by spacemeowx2** [comment]
清晰度在 API 中的定义是数字 0, 4, 2, 1; 参数名叫 `rate`

| rate | 原播放器 | 本播放器|
| :-: | :---: | :---: |
| 0 | 蓝光8M | 超清 |
| 4 | 蓝光4M | <无> |
| 2 | 高清 | 高清 |
| 1 | 标清 | 标清 |

注: 蓝光4M 本播放器暂时没有支持

**Comment by wangzhao2222** [comment]
你好，如果没有蓝光8M选项，播放器会自动选择蓝光4M吗？

**Comment by spacemeowx2** [comment]
本播放器超清就是最高清晰度, 就是没有重新压缩的流. 如果没有8M就是4M

**Comment by spacemeowx2** [comment]
斗鱼改了以后实际上就是把之前的超清加了个nM, 然后多压了个码率而已.
