### ISSUE TITLE
请问失效了吗？

### ISSUE THREAD

**Issue by waldens** [spacemeowx2/DouyuHTML5Player#90]
看没其他人反馈，不知道是我本地问题，还是确失效了

测试地址：https://www.douyu.com/11017
测试环境：Win7x64，百分浏览器版本 3.5.3.50（正式版本） （64 位） (portable) (Chromium 67.0.3396.99)
禁用其它所有扩展，以减少影响

之前都正常，从两三天前开始，启用扩展后，就不能观看（黑屏如下图），禁用后才能正常

![](http://onuia4d7l.bkt.clouddn.com/2018_09_09_20180909181502.png)

**Comment by spacemeowx2** [comment]
你这图下面都没了, 截图完整吗?

**Comment by waldens** [comment]
@spacemeowx2 这是笔记本电脑，屏幕就这么大，页面是完整的

后来又试了下，真奇怪，其它直播间都可以正常观看，唯独这个直播间不行（←现象描述），我怀疑是否跟缓存有关（←不靠谱推测），尝试清空了缓存和cookie也没用（完整的历史记录不方便清除）

后来卸载扩展，重新安装，就好了
